In [1]:
import torch

In [2]:
x = torch.randn(3)
print(x)

tensor([-0.7484, -2.1737,  0.1608])


***We want to calculate the gradient of some function with respect to X then we must specify the argument requires grad ***

In [3]:
x = torch.randn(3, requires_grad=True)
print(x) 

tensor([-0.3894, -0.6472, -1.1848], requires_grad=True)


In [4]:
# Now whenever we do operations with this tensor pi torch will create so called computational graph for us 

y = x+2 
print(y)
z = y*y*2
z = z.mean() # Our gradient fucntion is the mean backward 
print(z) 

z.backward() # Going to calculate dz/dx
print(x.grad) # Gradients are stored 


tensor([1.6106, 1.3528, 0.8152], grad_fn=<AddBackward0>)
tensor(3.3926, grad_fn=<MeanBackward0>)
tensor([2.1475, 1.8038, 1.0870])


***Preventing Gradient History***

In [5]:
# For preventing from tracking the gradients we have 3 options for this
# 1st -> x.requires_grad_(Flase)
# 2nd -> x.detach()
# 3rd -> with torch.no_grad()

In [6]:
# 1st

x.requires_grad_(False)
print(x)

# 2nd

y = x.detach()
print(y)

# 3rd

with torch.no_grad():
  y = x+2
  print(y)


# Those are the three ways how we can stop pytorch from creating this gradient fucntions 
# and tracking the history in our computational graph 

tensor([-0.3894, -0.6472, -1.1848])
tensor([-0.3894, -0.6472, -1.1848])
tensor([1.6106, 1.3528, 0.8152])


***Gradient for this tensor will be accumulated into .grad attributes their values will be summed up  ***

In [7]:
# Dummy training example 

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)


tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [8]:
# Incorrect gradients so we must empty the gradients 

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


***Pytorch's built-in optimizier*** 

In [10]:
import torch.nn as nn

# Define a simple model with learnable parameters
model = nn.Linear(4, 1)

# Pass the model parameters to the optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
optimizer.step()
optimizer.zero_grad()
