In [42]:
import torch
import numpy as np

In [43]:
# Creating an empty tensor

x = torch.empty(1) #Scalar value without initializing
print(x)


tensor([7.6040e-35])


In [44]:
# 1D vector with three elements 

x = torch.empty(3) 
print(x)


tensor([3.1393e-35, 0.0000e+00, 7.6812e-35])


In [45]:
# 2D matrix 

x = torch.empty(2,3)
print(x) 

tensor([[7.5997e-35, 0.0000e+00, 7.6043e-35],
        [0.0000e+00, 1.1125e+31, 4.5736e-41]])


In [46]:
# 3D 

x = torch.empty(2,2,3)
print(x)

tensor([[[1.9064e-05, 4.5737e-41, 8.0971e-35],
         [0.0000e+00, 4.4842e-44, 0.0000e+00]],

        [[1.5695e-43, 0.0000e+00, 6.0650e-35],
         [0.0000e+00, 7.6526e-35, 0.0000e+00]]])


In [47]:
# Creating a tensor with random values 

x = torch.rand(2,2)
print(x)

tensor([[0.8685, 0.4407],
        [0.0877, 0.5054]])


In [48]:
# Tensor with zeros / ones

x = torch.zeros(2,2)
print(x) 

tensor([[0., 0.],
        [0., 0.]])


In [49]:
# With datatype 

x = torch.ones(2,2, dtype=torch.int)
print(x.dtype)

# Size 

print(x.size())

torch.int32
torch.Size([2, 2])


***Some basic Operations with tensors***

In [50]:
# Element wise addition 

x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

z = x+y
z = torch.add(x,y) # Same as before
print(z)

tensor([[0.7914, 0.1836],
        [0.9277, 0.4024]])
tensor([[0.8933, 0.6679],
        [0.4676, 0.5496]])
tensor([[1.6847, 0.8515],
        [1.3953, 0.9520]])


**In pytorch trailing underscore will do an in-place operation so this will modify the variable that it is applied on**

In [51]:
# In place addition 

y.add_(x)
print(y) # It will modify our y and add all of the elements of x to our y



tensor([[1.6847, 0.8515],
        [1.3953, 0.9520]])


**Slicing Operations**

In [52]:
x = torch.rand(5,3)

print(x)

# All rows but only one column

print(x[:,0])

tensor([[0.8979, 0.9201, 0.0788],
        [0.2576, 0.5784, 0.9405],
        [0.9591, 0.7176, 0.0363],
        [0.8780, 0.0474, 0.9079],
        [0.0498, 0.1211, 0.3870]])
tensor([0.8979, 0.2576, 0.9591, 0.8780, 0.0498])


***Reshaping an tensor***

In [53]:
x = torch.rand(4,4)
print(x)

y = x.view(16) 
print(y)

print(y.size())

tensor([[0.1736, 0.0272, 0.1923, 0.8262],
        [0.9221, 0.9246, 0.5934, 0.2992],
        [0.6008, 0.4942, 0.8346, 0.9516],
        [0.1674, 0.6972, 0.3212, 0.4969]])
tensor([0.1736, 0.0272, 0.1923, 0.8262, 0.9221, 0.9246, 0.5934, 0.2992, 0.6008,
        0.4942, 0.8346, 0.9516, 0.1674, 0.6972, 0.3212, 0.4969])
torch.Size([16])


***Numpy to torch***

In [54]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(type(b))


tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


In [58]:
# Torch to numpy

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a+=1
print(a)
print(b) # Tensor is on GPU 

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
